"""
Module 5 - Privilege Detection.

Scans every document in forensic.db for indicators of attorney-client
privilege or work product protection, sets is_privileged = 1 on flagged
documents, and writes a PRIVILEGE_LOG.md listing every withheld document.

Two detection methods run in combination:

  Attorney domain matching: if the sender or any recipient has an email
  address at a domain listed in config/attorney_domains.txt, the document
  is flagged. A lawyer being on a correspondence is the primary indicator
  of attorney-client privilege in practice.

  Keyword matching: subject and body are scanned for phrases listed in
  config/privilege_keywords.txt (e.g. "privileged and confidential",
  "outside counsel", "work product"). Flagged without an attorney domain
  present, these produce a "Potentially Privileged" basis — over-inclusive
  by design, requiring human review to confirm.

Re-running resets all previous privilege flags before re-scanning, so
updating the keyword or domain lists and re-running gives a clean result.

Run from the repository root with:
    python -m output.privilege_log
"""

import sqlite3
from datetime import datetime, timezone
from pathlib import Path

from ingestion.metadata_store import get_connection

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_KEYWORDS_PATH = REPO_ROOT / "config" / "privilege_keywords.txt"
DEFAULT_DOMAINS_PATH = REPO_ROOT / "config" / "attorney_domains.txt"
PRIVILEGE_LOG_PATH = REPO_ROOT / "PRIVILEGE_LOG.md"


def load_lines(path: Path) -> list[str]:
    """Read non-empty, non-comment lines from a config file."""
    if not path.exists():
        raise FileNotFoundError(f"Config file not found: {path}")
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


def load_privilege_keywords(path: Path = DEFAULT_KEYWORDS_PATH) -> list[str]:
    return load_lines(path)


def load_attorney_domains(path: Path = DEFAULT_DOMAINS_PATH) -> set[str]:
    return set(load_lines(path))


def _extract_domains(address_field: str) -> list[str]:
    """Extract email domains from a semicolon-separated address field."""
    domains = []
    for addr in (address_field or "").split(";"):
        addr = addr.strip()
        if "@" in addr:
            domains.append(addr.split("@")[-1].lower().strip(">").strip())
    return domains


def detect_privilege(
    row: dict,
    keywords: list[str],
    attorney_domains: set[str],
) -> tuple[bool, str]:
    """Return (is_privileged, basis) for a single document."""
    all_domains: list[str] = []
    for field in ("sender", "recipients_to", "recipients_cc", "recipients_bcc"):
        all_domains.extend(_extract_domains(row.get(field) or ""))

    attorney_present = any(d in attorney_domains for d in all_domains)

    combined = f"{row.get('subject') or ''} {row.get('body_text') or ''}".lower()
    kw_hits = [kw for kw in keywords if kw.lower() in combined]
    has_work_product = "work product" in combined

    if attorney_present:
        return True, "Attorney-Client Privilege"
    if has_work_product:
        return True, "Work Product"
    if kw_hits:
        return True, "Potentially Privileged"

    return False, ""


def flag_documents(
    conn: sqlite3.Connection,
    keywords: list[str],
    attorney_domains: set[str],
) -> list[dict]:
    """Detect privilege on all documents. Returns list of flagged doc dicts."""
    conn.execute("UPDATE documents SET is_privileged = 0, review_tag = NULL")
    conn.commit()

    rows = conn.execute(
        "SELECT id, custodian, date_sent, sender, "
        "recipients_to, recipients_cc, recipients_bcc, subject, body_text "
        "FROM documents"
    ).fetchall()

    flagged = []
    updates = []

    for row in rows:
        row = dict(row)
        is_priv, basis = detect_privilege(row, keywords, attorney_domains)
        if is_priv:
            flagged.append({**row, "basis": basis})
            updates.append((1, basis, row["id"]))

    if updates:
        conn.executemany(
            "UPDATE documents SET is_privileged = ?, review_tag = ? WHERE id = ?",
            updates,
        )
        conn.commit()

    return flagged


def write_privilege_log(flagged: list[dict]) -> None:
    """Write PRIVILEGE_LOG.md — the formal record of withheld documents."""
    header = (
        "# Privilege Log\n\n"
        "Generated by `output/privilege_log.py`. "
        "Lists every document withheld or flagged as potentially privileged. "
        "In a real matter, this log is provided to opposing counsel in lieu "
        "of the actual documents.\n\n"
        f"Generated: {datetime.now(timezone.utc).isoformat()}\n\n"
        "| Item ID | Custodian | Date Sent | Sender | Recipients (To) | Subject Description | Privilege Basis |\n"
        "|---|---|---|---|---|---|---|\n"
    )

    rows = []
    for doc in flagged:
        date = (doc.get("date_sent") or "")[:10]
        sender = doc.get("sender") or ""
        to = (doc.get("recipients_to") or "").split(";")[0].strip()
        subject = (doc.get("subject") or "(no subject)")[:60]
        rows.append(
            f"| {doc['id']} | {doc['custodian']} | {date} | {sender} "
            f"| {to} | {subject} | {doc['basis']} |"
        )

    PRIVILEGE_LOG_PATH.write_text(header + "\n".join(rows) + "\n", encoding="utf-8")


def print_summary(flagged: list[dict], conn: sqlite3.Connection) -> None:
    total = conn.execute("SELECT COUNT(*) FROM documents").fetchone()[0]
    n = len(flagged)

    basis_counts: dict[str, int] = {}
    for doc in flagged:
        basis_counts[doc["basis"]] = basis_counts.get(doc["basis"], 0) + 1

    custodian_counts: dict[str, int] = {}
    for doc in flagged:
        custodian_counts[doc["custodian"]] = custodian_counts.get(doc["custodian"], 0) + 1

    print("=" * 60)
    print("PRIVILEGE DETECTION SUMMARY")
    print("=" * 60)
    print(f"Total documents:                {total}")
    print(f"Privileged / withheld:          {n} ({n / total:.1%})")
    print(f"Cleared for review:             {total - n} ({(total - n) / total:.1%})")
    print()
    print("By privilege basis:")
    for basis, count in sorted(basis_counts.items(), key=lambda x: -x[1]):
        print(f"  {basis:<35} {count}")
    print()
    print("By custodian:")
    for custodian, count in sorted(custodian_counts.items()):
        total_cust = conn.execute(
            "SELECT COUNT(*) FROM documents WHERE custodian = ?", (custodian,)
        ).fetchone()[0]
        print(f"  {custodian}: {count}/{total_cust} ({count / total_cust:.1%})")
    print()
    print(f"Privilege log written to: PRIVILEGE_LOG.md")
    print("=" * 60)


def run_privilege_detection(
    keywords_path: Path = None,
    domains_path: Path = None,
    db_path: Path = None,
) -> None:
    keywords = load_privilege_keywords(keywords_path or DEFAULT_KEYWORDS_PATH)
    attorney_domains = load_attorney_domains(domains_path or DEFAULT_DOMAINS_PATH)
    conn = get_connection(db_path) if db_path else get_connection()
    flagged = flag_documents(conn, keywords, attorney_domains)
    write_privilege_log(flagged)
    print_summary(flagged, conn)
    conn.close()


if __name__ == "__main__":
    run_privilege_detection()
